version: '3'
services:
# Services
  Base:
    image: "reg.ci.snsshop.net/opt/dev/service-base:001"
    networks:
      - opt-net
    volumes:
      - "/data/opt/dev/service-base/logs:/data/www/runtime/logs"
    extra_hosts:
      - "imgcaches.vikduo.com:10.100.100.35"
  Qrcode:
    image: "reg.ci.snsshop.net/opt/dev/service-qrcode:001"
    networks:
      - opt-net
    volumes:
      - "/data/opt/dev/service-qrcode/logs:/data/www/runtime/logs"
    extra_hosts:
      - "imgcaches.vikduo.com:10.100.100.35"
  ThirdPartyInterface:
    image: "reg.ci.snsshop.net/opt/dev/service-third-party-interface:001"
    networks:
      - opt-net
    volumes:
      - "/data/opt/dev/service-third-party-interface/logs:/data/www/runtime/logs"
  gateway-app-merchant:
    image: "reg.ci.snsshop.net/opt/dev/gateway-app-merchant:001"
    networks:
      - opt-net
    volumes:
      - "/data/opt/dev/gateway-app-merchant/logs:/data/www/runtime/logs"
    extra_hosts:
      - "imgcaches.vikduo.com:10.100.100.35"
  gateway-app-salesman:
    image: "reg.ci.snsshop.net/opt/dev/gateway-app-salesman:001"
    networks:
      - opt-net
    volumes:
      - "/data/opt/dev/gateway-app-salesman/logs:/data/www/runtime/logs"
    extra_hosts:
      - "imgcaches.vikduo.com:10.100.100.35"
  gateway-boss:
    image: "reg.ci.snsshop.net/opt/dev/gateway-boss:001"
    networks:
      - opt-net
    volumes:
      - "/data/opt/dev/gateway-boss/logs:/data/www/runtime/logs"
    extra_hosts:
      - "imgcaches.vikduo.com:10.100.100.35"
networks:
  opt-net:
